### ISSUE TITLE
[Feature Request] second Variable instead of characters use lines

### ISSUE THREAD

**Issue by Jaglag** [ClaudeBot/hubot-longtext#3]
For example a link have a very long url and hubot try to send it 3 times a setting of 3-500 isnt still enough to handle it correctly.
So instead of a maximum of characters do a maximum of lines per command ouptutted before dpaste gets triggered. so these 3 urls are just 3 lines and fits normally in every client in 3 lines, but dpaste gets triggered with maximum charcater that way.

**Comment by MrSaints** [comment]
I don't quite understand you. Correct me if I'm wrong, but basically you want it to check for total number of lines as well?

**Comment by Jaglag** [comment]
yes basicly HUBOT_LONGTEXT_MAX_LINES="x"
instead of max characters before he triggers dpaste.

**Comment by MrSaints** [comment]
Yeah, I think this is a good feature request.

I'll work on it if I have the time, otherwise, I'd love if someone could help :tired_face: 

It's as simple as checking for the length of `context.strings`

**Comment by Jaglag** [comment]
sry i cannot help with stuff like that :cry:

**Comment by MrSaints** [comment]
@Jaglag can you give me a sample data / message for me to test? You can PM me.

**Comment by Jaglag** [comment]
@MrSaints !help or for example try to block the output from dota history and set dpaste to 4 lines and if that works back to 5 lines

**Comment by Jaglag** [comment]
https://github.com/Jaglag/Butlerz/blob/master/scripts/redditbomb.coffee

this script gets blocked by dpaste too but it should be only 5 lines like dota history
